services:
  - type: web
    name: cybernova-analytics
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres
      - key: DB_USER
        value: postgres.xsgzgfrrulcnemkywxpi
      - key: DB_PASSWORD
        sync: false
